@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzUyOTk2NTcwLCJleHAiOjE3NTMwODI5NzB9.U2OWvftEgR289eu_43q3oxbbOMKyj0B_Rw8rp16pe_g

### 
GET http://localhost:51540/1

### Register
POST http://localhost:51540/auth/register
Content-Type: application/json

{
    "username": "user2",
    "email": "kirayoshikage@gmail.com",
    "password": "June152005!",
}

### Login
POST http://localhost:51540/auth/login
Content-Type: application/json

{
    "email": "anggand@gmail.com",
    "password": "143lencel"
}

### Get Customers (Protected)
GET http://localhost:51540/customers
Authorization: Bearer {{token}}

### Get Customers (Protected)
GET http://localhost:51540/customers/1
Authorization: Bearer {{token}}

### staff dashboard
GET http://localhost:51540/dashboard
Authorization: Bearer {{token}}
 
### get user profile
GET http://localhost:51540/profile
Authorization: Bearer {{token}}
### get user profile
GET http://localhost:51540/foods
Authorization: Bearer {{token}}

### Login
POST http://localhost:51540/orders/confirm
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "customer_id": 4,
    "food_ids": [],
    "reward_code": "3BJPYpOZb8"
}

### get user profile
GET http://localhost:51540/customers/top
Authorization: Bearer {{token}}

### get user profile
GET http://localhost:51540/customers/customer/allCust
Authorization: Bearer {{token}}

### get user profile
GET http://localhost:51540/staff
Authorization: Bearer {{token}}

### get user profile
GET http://localhost:51540/admin
Authorization: Bearer {{token}}

### get user profile
PUT  http://localhost:51540/staff/update/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "Chaewon",
    "email": "chaewonbaby"
}
### get user profile
DELETE http://localhost:51540/customers/delete/9
Authorization: Bearer {{token}}
### get user profile
DELETE http://localhost:51540/staff/delete/9
Authorization: Bearer {{token}}

### get user profile
GET http://localhost:51540/feedback/star-distribution
Authorization: Bearer {{token}}

### get user profile
GET http://localhost:51540/orders/foods/sales
Authorization: Bearer {{token}}

### get user profile
GET http://localhost:51540/rewards/redemptions
Authorization: Bearer {{token}}


### get user profile
GET http://localhost:51540/feedback/
Authorization: Bearer {{token}}

